---
name: NOP
main: NETÝKÁ SE TÉTO DOHODY
version: 1.6.4
description: 1.15.2 Minecraft protikžár
api-version: 1.15
author: MSWS
softdepend:
  - ProtocolLib
  - MaxBany
  - Pokročilý Ban
  - LapisBany
  - LiteBans
  - Správa bannerů
  - Zástupné API
  - mcMMO
  - Crazyenchanty
  - Tréninkové vozy
  - Tréninkový košík
commands:
  NOPE:
    usage: /<command>
    aliases:
      - ac
      - anticheat
permissions:
  nope.*:
    description: Umožňuje přístup ke všem funkcím NOP a obchází všechny kontroly NOPE
  nope.bypass.movement:
    description: Umožňuje hráči obejít všechny kontroly pohybu
  nope.bypass.flight:
    description: Umožňuje hráči obejít všechny kontroly letu
  "nope.bypass.movement.flight#4":
    description: 'Umožňuje hráči obejít veškerý let#4 kontrolu'
  nope.command.toggle.scoreboard:
    description: Umožňuje hráči přepnout vlastní tabulku skóre
  nope.command.toggle.gscoreboard:
    description: Umožňuje přehrávači přepnout skóre serveru
  nope.command.testlag:
    description: Umožňuje hráči přístup k příkazu testlag
