---
name: NOTE
main: NOUVEAU
version: 1.6.4
description: 1.15.2 Minecraft Anticheat
api-version: 1.15
author: MSWS
softdepend:
  - ProtocolLib
  - Bannissements MaxBans
  - Ban avancé
  - LapisBans
  - LiteBans
  - Gestion des banquiers
  - PlaceholderAPI
  - mcMMO
  - Enchantements
  - Chariots d'entraînement
  - Paniers de train
commands:
  NOPE:
    usage: /<command>
    aliases:
      - ac
      - anticheat
permissions:
  nope.*:
    description: Donne accès à toutes les fonctionnalités NOPEs et contourne toutes les vérifications NOPE
  nope.bypass.movement:
    description: Permet au joueur de contourner tous les tests de déplacement
  nope.bypass.flight:
    description: Permet au joueur de contourner toutes les vérifications de vol
  "nope.bypass.movement.flight#4":
    description: 'Permet au joueur de contourner tous les tests de vol #4'
  nope.command.toggle.scoreboard:
    description: Permet au joueur de basculer son propre tableau de scores
  nope.command.toggle.gscoreboard:
    description: Permet au joueur d'activer/désactiver le tableau de bord du serveur
  nope.command.testlag:
    description: Permet au joueur d'accéder à la commande testlag
