files:
  - source: /src/*
    translation: /t/%language%/%original_path%/%original_file_name%
  - source: /*.yml
    translation: /t/%language%/%original_path%/%original_file_name%
  - source: /*.xml
    translation: /t/%language%/%original_path%/%original_file_name%
