---
name: NOPER
main: xyz.msws.nope.NOPE
version: 1.7.2
description: 1.15.2-1.16.1 Minecraft Anticheat
api-version: 1.14
author: MSWS
softdepend:
  - ProtocolLib
  - MaxBans
  - Bloqueo avanzado
  - Lapisban
  - LiteBans
  - Gestión de bananos
  - PlaceholderAPI
  - mcMMO
  - Encantamientos locos
  - Train_Carts
commands:
  NOPE:
    usage: /<command>
    aliases:
      - ac
      - anticheat
      - ncp
permissions:
  nope.*:
    description: Da acceso a todas las características de NOPEs y evita todas las comprobaciones de NOPE
  nope.bypass.movement:
    description: Permite al jugador eludir todas las comprobaciones de movimiento
  nope.bypass.flight:
    description: Permite al jugador eludir todas las comprobaciones de vuelo
  "nope.bypass.movement.flight#4":
    description: 'Permite al jugador eludir todas las comprobaciones de vuelo#4'
  nope.command.toggle.scoreboard:
    description: Permite al jugador cambiar su propio marcador
  nope.command.toggle.gscoreboard:
    description: Permite al jugador cambiar el marcador del servidor
  nope.command.testlag:
    description: Permite al jugador acceder al comando testlag
  nope.command.false:
    description: Allows the player access to the false command
