---
name: NU
main: xyz.msws.nope.nPE
version: 1.7.2
description: 1.15.2-1.16.1 Minecraft Anticheat
api-version: 1.14
author: MWOON
softdepend:
  - ProtocolLib
  - MaxBans
  - AdvancedBan
  - LapisBans
  - LiteBans
  - Banenbeheer
  - PlaceholderAPI
  - mcMMO
  - CrazyBetoveringen
  - Train_Carts
commands:
  NOPE:
    usage: /<command>
    aliases:
      - ac
      - anticheat
      - ncp
permissions:
  nope.*:
    description: Geeft toegang tot alle NOPEs-functies en passaties alle NOPE-controles
  nope.bypass.movement:
    description: Hiermee kan de speler alle bewegingscontroles omzeilen
  nope.bypass.flight:
    description: Hiermee kan de speler alle vluchtcontroles omzeilen
  "nope.bypass.movement.flight#4":
    description: "Hiermee kan de speler alle controles omzeilen #4"
  nope.command.toggle.scoreboard:
    description: Laat de speler zijn eigen scorebord in- of uitschakelen
  nope.command.toggle.gscoreboard:
    description: Staat de speler toe om het scorebord van de server om te schakelen
  nope.command.testlag:
    description: Staat de speler toegang toe tot de testlag opdracht
  nope.command.false:
    description: Allows the player access to the false command
