---
#----------------------------------------------------------
#NOPE Anti-Cheat Configuration
#This is the configuration for NOPE. I recommend keeping
#the default values unless you know what you're doing.
#There is a YouTube tutorial available at
#https://www.youtube.com/watch?v=XVuXKsJEAkQ
#There is a GitHub wiki tutorial also
#available at https://NOPE.MSWS.xyz/wiki
#----------------------------------------------------------
ConfigVersion: 1.7.2
#-------------------------------
#Global Configuration
#-------------------------------
Global: true #If disabled, NOPE will be disabled
Scoreboard: true
Log: 文件 #NONE, file, or hastebin
#Permission to be notified ingame is nope.message.udpate
UpdateChecker:
  Enabled: true
  InGame: true
BungeeNameOverride: "" #If not empty this will override the server name
#This is useful for replacing %server% if the server is not bungeecord
#VL Decrement is responsible for decrementing VL levels for players that haven't flagged for a while
#The key is the time in milliseconds since the player last flagged for a hack. For example
#if a player hasn't flagged for 20000 milliseconds, their VL will be decreased by 2 every second
VLDecrement:
  Enabled: true
  Rate: 40 #Ticks
  Periods:
    1000: 0
    10000: 1
    20000: 2
    60000: 5
    120000: 10
    -1: 20
#-------------------------------
#Banwave Configuration
#-------------------------------
BanwaveRate: 36000 #Rate of banwave (in ticks) -1 to disable
#If enabled, developer messages will be sent to the player and commands will not execute
DevMode: false
DebugMode: false
#-------------------------------
#Webhook Configuration
#Webhooks allow a server to send POST requests to a webhook.
#If you do not know about this then I recommend
#Googling or asking someone for help regarding this.
#For Discord specific configuration you can look at
#https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html
#and https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks?page=1
#for help. All arguments are supported that are defined in the first link.
#Placeholders listed below in Actions are supported
#-------------------------------
Webhooks:
  banExample:
    URL: "https://discordapp.com/api/webhooks/"
    username: "无"
    avatar_url: "https://i.imgur.com/JLKC7CN.jpg"
    embeds:
      author:
        name: "%player% 封禁"
        avatar_url: "https://i.imgur.com/JLKC7CN.jpg"
      title: "%player% 在 %check% 被封禁"
      color: 14483456
      fields:
        check:
          name: "检查"
          value: "%debug%"
        world:
          name: "世界"
          value: "%world%"
        vl:
          name: "虚拟机"
          value: "%vl%"
          inline: false
  flagExample:
    URL: "https://discordapp.com/api/webhooks/"
    username: "无"
    avatar_url: "https://i.imgur.com/JLKC7CN.jpg"
    embeds:
      author:
        name: "%player%"
        icon_url: "https://crafatar.com/avatars/%uuid%"
      title: "%player% 标记了 %check%"
      color: 751818
      fields:
        1:
          name: "播放器"
          value: "%player%"
        2:
          name: "世界"
          value: "%world%"
        3:
          name: "服务器"
          value: "%server%"
          inline: true
        4:
          name: "虚拟机"
          value: "%vl%"
        5:
          name: "检查"
          value: "%debug%"
        6:
          name: "UUID"
          value: "%uuid%"
      #thumbnail:
      #url: ''
      #image:
      #url: ''
      footer:
        text: "MSWS.XYZ"
#icon_url: ''
#-------------------------------
#Action Configuration
#Please note that bans are not necesssarily instantaneous.
#Please add a delay to prevent duplicate bans.
#animation:[TYPE]:Action         | TYPEs are NOPE or GWEN, the Action should be a custom command
#kick:Reason                     | Kick the player for the specified reason
#ban:Time:Reason                 | Ban the player for the specified time/reason
#banwave:Time:Reason             | Add the player to the banwave
#cancel                          | Teleport the player back
#pmsg:[Message]                  | Send a message to the player
#msg:[all/Permission]:[Message]  | Can also specify all
#cmd:[Command]                   | Run a command as the player
#ccmd:[Command]                  | Run a command from console
#log:type:message                | Logs the message either to FILE, INGAME, or CONSOLE (perm: nope.message.normal)
#log:WEBHOOK:message             | Logs the message to the specified webhook
#setvl:VL                        | Sets the player's VL for the category hack
#addvl:VL                        | Adds/Modifies the player's VL for the category hack
#Conditions: (<, <=, =, !=, >=, >)
#If a condition is not fullfilled, none of the following actions will be run
#The ones with > you can replace with the appropriate operator
#vl>[Amo]       | If the VL matches the threshold
#tps>[Amo]      | If the server's TPS matches the threshold
#ping>[Amo]     | If the player's ping matches (NOT RECOMMENDED) players can spoof their ping
#delay:[Delay]  | Wait X milliseconds before executing the NEXT action (eg: kick a player if the last call of this was > 60 seconds ago)
#notdev         | Will not run the next actions if the in dev mode
#isdev          | Will run the next actions if in dev mode
#rnd:.40        | Will run the actions 40% of the time
#Placeholders
#%player%  | The name of the player that was banned
#%uuid%    | The UUID of the player (-'s included)
#%nuuid%   | The UUID of the player (-'s not included)
#%check%   | What hack the player was banned for
#%debug%   | The debug ID of the check
#%vl%      | The VL of the hack that the player was at when they were banned
#%world%   | What world the player was in when they were banned, this may be null if they were offline
#%token%   | The ban token (only for ban)
#%server%  | The server name, useful for webhooks
#PAPI is also supported
#-------------------------------
Actions:
  FastBreak:
    - "basiclog|canclog|vl>100|tpsdeclarment|delay:40000|tpskick|vl>400|延迟：20000|lagkick|flog|log:FILE:Kicked %player% for %check%|tps>15|vl>600|cban"
  FastClimb:
    - "basiclog|vl>50|延迟：500|cancel|vl>200|cancel|vl>400|ikick|vl>600|cban"
  Blink:
    - "基本日志|vl>200|延迟：2000|取消|延迟：15000|tpsDeclarment|tps>15|vl>250|lagkick|vl>500|取消|vl>800|cban"
  NoSwing:
    - "基本log|vl>500|ikick|vl>1000|cban"
  Speed:
    - "基本日志|rndcancel|vl>100|cancel|vl>800|addbanwave|vl>1200|cban"
  ElytraFlight:
    - "基本日志|vl>500|ikick|vl>800|addbanwave|vl>1000|cban"
  Timer:
    - "basiclog|vl>300|rndcancel|延迟：10000|tpsdeclarment|vl>500|lagkick|vl>600|ikick|vl>800|cban"
  KillAura:
    - "基本日志|vl>200|ikick|vl>500|延迟：120000|kick:Irregular Gameplay|vl>600|cban"
  NoFall:
    - "基本log|vl>300|ikick|vl>800|cban"
  SafeWalk:
    - "基本log|vl>500|ikick"
  Default:
    - "basiclog|vl>20|cancel|vl>100|flog|vl>200|lagkick|tps>15|vl>400|ikick|vl>800|addbanwave|vl>1200|cban"
#You can specify multiple actiongroups for one category
#- 'vl>50|delay:10000|ccmd:say %player% is suspected of using %check%'
#This would only kick players and decrement their VL by 200
#- 'basiclog|vl>100|cancel|vl>600|ikick|addvl:-200'
#You can also specify a specific debug name and that these actions will be run instead
#Flight#3:
#- 'basiclog|delay:60000|say %player% flagged a %debug% check!'
#Commands are loaded and created in order. Define a custom command first before using it in another custom command.
Commands:
  #log Logs to a file that the player failed a check, and logs in console every 5 seconds that they failed the check
  flog: "log:FILE:%player% 失败 %debug% (%vl%)|延迟:5000|log:CONSOLE:%player% 失败 %debug%"
  #the below actions log ingame an appropriate warning message to staff
  alog: "vl>100|vl<300|延迟：60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7失败&a%check%&7 check。(VL: &e%vl%&7)"
  elog: "vl>300|vl<500|延迟：60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7失败&e%check%&e 7 check。(&e%vl%&7)"
  clog: "vl>500|vl<700|延迟：60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7失败&c%check%&7 check。(&e%vl%&7)"
  4log: "vl>700|延迟：500|flog|延迟：60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7失败 &4%check%&7 check。(VL: &e%vl%&7)"
  #weblog Logs the action to the specified webhook (in this case flagExample)
  weblog: "notdev|vl>400|延迟:120000|log:flag例如："
  #basiclog combines all above log commands into 1 for simple usage
  basiclog: "|elog|blog|flog|4log|weblog"
  #logban Logs ingame that the player was banned both ingame and to a file
  logban: "log:INGAME:&4&l[&c&lNOPE&4&l] &c%player% &7被封禁于&b%check%&7.|log:FILE:封禁 %player% %debug% %vl%|延迟:5000|log:ban示例:"
  #ikick Kicks the player once every minute (to avoid constant kicking) in case they are stuck/otherwise false flagging
  ikick: "notdev|delay:60000|kick:Irregular Gameblay"
  #lagkick Kicks the player if their ping is too high
  lagkick: "ping>150|kick:您似乎很落后，请尝试重新启动您的连接。"
  #tpskick Kicks the player if the server's TPS is too low
  tpskick: "tps<=16|kick:服务器过于落后，请尝试稍候后再重新登录。"
  tpsdecrement: "tps<=16|addvl:-50"
  #rndcancel Has an 80% chance of teleporting the player back
  rndcancel: "rnd:.80|取消"
  canimate: "blogban|ban:26280000:&4NOPE Anti-Cheat&r\n&7Token: &e%token%"
  #cban Only bans the player if dev mode is disabled, it also logs the ban
  #We log the ban first so we can get the VL data first
  cban: "notdev|延迟：5000|动画：NOPE：canimate"
  addbanwave: "notdev|banwave:26280000:&4NOPE Anti-Cheat&r\n&7Token: &e%token%"
#-------------------------------
#Check Configuration
#Here you can configure which checks are/aren't enabled
#You can also toggle these ingame with /nope stats
#make sure to restart your server after modifying these settings
#-------------------------------
Checks:
  Packet:
    Enabled: true
    SkinBlinker:
      Enabled: true
      "SkinBlinker#1":
        Enabled: true
    Spinbot:
      Enabled: true
      "Spinbot#1":
        Enabled: true
    NoSwing:
      Enabled: true
      "NoSwing#1":
        Enabled: true
    PlayerESP:
      Enabled: true
      "PlayerESP#2":
        Enabled: true
      "PlayerESP#1":
        Enabled: true
    AutoSneak:
      Enabled: true
      "AutoSneak#1":
        Enabled: true
    InvalidMovement:
      Enabled: true
      "InvalidMovement#1":
        Enabled: true
    Timer:
      Enabled: true
      "Timer#1":
        Enabled: true
    Blink:
      Enabled: true
      "Blink#1":
        Enabled: true
  Movement:
    Enabled: true
    Speed:
      Enabled: true
      "Speed#3":
        Enabled: true
      "Speed#4":
        Enabled: true
      "Speed#1":
        Enabled: true
      "Speed#5":
        Enabled: true
      "Speed#2":
        Enabled: true
    InventoryMove:
      Enabled: true
      "InventoryMove#1":
        Enabled: true
    FastSneak:
      Enabled: true
      "FastSneak#1":
        Enabled: true
    AutoWalk:
      Enabled: true
      "AutoWalk#1":
        Enabled: true
    Glide:
      Enabled: true
      "Glide#1":
        Enabled: true
    Flight:
      Enabled: true
      "Flight#6":
        Enabled: true
      "Flight#1":
        Enabled: true
      "Flight#4":
        Enabled: true
      "Flight#2":
        Enabled: true
      "Flight#5":
        Enabled: true
      "Flight#3":
        Enabled: true
    BHop:
      Enabled: true
      "BHop#1":
        Enabled: true
    ElytraFlight:
      Enabled: true
      "ElytraFlight#1":
        Enabled: true
    AntiRotate:
      Enabled: true
      "AntiRotate#1":
        Enabled: true
    Jesus:
      Enabled: true
      "Jesus#1":
        Enabled: true
      "Jesus#2":
        Enabled: true
    AntiAFK:
      Enabled: true
      "AntiAFK#1":
        Enabled: true
    NoSlowDown:
      Enabled: true
      "NoSlowDown#1":
        Enabled: true
      "NoSlowDown#2":
        Enabled: true
      "NoSlowDown#5":
        Enabled: true
      "NoSlowDown#3":
        Enabled: true
      "NoSlowDown#4":
        Enabled: true
    Step:
      Enabled: true
      "Step#1":
        Enabled: true
    Spider:
      Enabled: true
      "Spider#1":
        Enabled: true
    NoWeb:
      Enabled: true
      "NoWeb#1":
        Enabled: true
    ClonedMovements:
      Enabled: true
      "ClonedMovement#1":
        Enabled: true
    FastClimb:
      Enabled: true
      "FastClimb#1":
        Enabled: true
  Combat:
    Enabled: true
    HighCPS:
      Enabled: true
      "HighCPS#1":
        Enabled: true
      "HighCPS#3":
        Enabled: true
      "HighCPS#2":
        Enabled: true
    AutoClicker:
      Enabled: true
      "AutoClicker#1":
        Enabled: true
    AntiKB:
      Enabled: true
      "AntiKB#1":
        Enabled: true
    AutoArmor:
      Enabled: true
      "AutoArmor#1":
        Enabled: true
    KillAura:
      Enabled: true
      "KillAura#3":
        Enabled: true
      "KillAura#5":
        Enabled: true
      "KillAura#2":
        Enabled: true
      "KillAura#4":
        Enabled: true
      "KillAura#1":
        Enabled: true
    FastBow:
      Enabled: true
      "FastBow#1":
        Enabled: true
  Player:
    Enabled: true
    NoFall:
      Enabled: true
      "NoFall#1":
        Enabled: true
      "NoFall#2":
        Enabled: true
    AutoTool:
      Enabled: true
      "AutoTool#1":
        Enabled: true
    GhostHand:
      Enabled: true
      "GhostHand#1":
        Enabled: true
    SafeWalk:
      Enabled: true
      "SafeWalk#1":
        Enabled: true
    AntiFire:
      Enabled: true
      "AntiFire#1":
        Enabled: true
    FastEat:
      Enabled: true
      "FastEat#1":
        Enabled: true
    SelfHarm:
      Enabled: true
      "SelfHarm#1":
        Enabled: true
    Zoot:
      Enabled: true
      "Zoot#1":
        Enabled: true
    HealthTag:
      Enabled: true
      "HealthTag#1":
        Enabled: true
  World:
    Enabled: true
    Scaffold:
      Enabled: true
      "Scaffold#3":
        Enabled: true
      "Scaffold#1":
        Enabled: true
      "Scaffold#2":
        Enabled: true
    AutoBuild:
      Enabled: true
      "AutoBuild#1":
        Enabled: true
    IllegalBlockPlace:
      Enabled: true
      "IllegalBlockPlace#1":
        Enabled: true
    FastBreak:
      Enabled: true
      "FastBreak#1":
        Enabled: true
    IllegalBlockBreak:
      Enabled: true
      "IllegalBlockBreak#1":
        Enabled: true
