---
name: NOPE
main: xyz.msws.nope.NOPE
version: 1.6.4
description: 1.15.2 Minecraft Anticheat
api-version: 1.15
author: MSWS
softdepend:
  - ProtocolLib
  - MaxBans
  - AdvancedBan
  - LapisBans
  - LiteBans
  - BanManagement
  - PlaceholderAPI
  - mcMMO
  - CrazyEnchantments
  - TrainCarts
  - Train_Carts
commands:
  NOPE:
    usage: /<command>
    aliases:
      - ac
      - anticheat
permissions:
  nope.*:
    description: Gives access to all of NOPEs features and bypasses all NOPE checks
  nope.bypass.movement:
    description: Allows the player to bypass all movement checks
  nope.bypass.flight:
    description: Allows the player to bypass all flight checks
  "nope.bypass.movement.flight#4":
    description: "Allows the player to bypass all flight#4 checks"
  nope.command.toggle.scoreboard:
    description: Allows the player to toggle their own scoreboard
  nope.command.toggle.gscoreboard:
    description: Allows the player to toggle the server's scoreboard
  nope.command.testlag:
    description: Allows the player access to the testlag command
