---
name: NOPE
main: xyz.msws.nope.NOPE
version: 1.6.4
description: 1.15.2 Minecraft Anticheat
api-version: 1.15
author: MSWS
softdepend:
  - ProtocolLib
  - MaxBans
  - Avansator
  - LapisBani
  - LiteBans
  - Gestionare banale
  - PlaceholderAPI
  - mcMMO
  - CrazyEnchantments
  - Antrenor
  - Cosuri
commands:
  NOPE:
    usage: /<command>
    aliases:
      - ac
      - anticheat
permissions:
  nope.*:
    description: Permite accesul la toate caracteristicile NOPE-urilor și ocolește toate verificările NOPE
  nope.bypass.movement:
    description: Permite jucătorului să ocolească toate verificările mișcării
  nope.bypass.flight:
    description: Permite jucătorului să ocolească toate verificările de zbor
  "nope.bypass.movement.flight#4":
    description: 'Permite jucătorului să treacă peste toate verificările zborului #4'
  nope.command.toggle.scoreboard:
    description: Permite jucătorului să își comode propriul tablou de bord
  nope.command.toggle.gscoreboard:
    description: Permite jucătorului să comute tabloul de bord al serverului
  nope.command.testlag:
    description: Permite jucătorului să acceseze comanda de testare
