---
name: INGEN
main: xyz.msws.nope.NOPE
version: 1.6.4
description: 1.15.2 Minecraft Anticheat
api-version: 1.15
author: MSWS
softdepend:
  - ProtocolLib
  - MaxBans
  - AdvancedBan
  - Bannlysningar
  - LiteBans
  - Banförvaltning
  - PlaceholderAPI
  - mcMMO
  - CrazyEnchantments
  - Varukorgar
  - Varukorgar
commands:
  NOPE:
    usage: /<command>
    aliases:
      - ac
      - anticheat
permissions:
  nope.*:
    description: Ger tillgång till alla NOPEs funktioner och kringgår alla NOPE kontroller
  nope.bypass.movement:
    description: Tillåter spelaren att kringgå alla förflyttningskontroller
  nope.bypass.flight:
    description: Tillåter spelaren att kringgå alla flygkontroller
  "nope.bypass.movement.flight#4":
    description: 'Tillåter spelaren att kringgå alla flyg#4 kontroller'
  nope.command.toggle.scoreboard:
    description: Tillåter spelaren att växla sin egen resultattavla
  nope.command.toggle.gscoreboard:
    description: Tillåter spelaren att växla serverns resultattavla
  nope.command.testlag:
    description: Ger spelaren tillgång till testlag-kommandot
