---
name: NOPE
main: xyz.msws.nope.NOPE
version: 1.7.2
description: 1.15.2-1.16.1 Minecraft Anticheat
api-version: 1.14
author: MSWS
softdepend:
  - ProtocolLib
  - MaxBans
  - AdvancedBan
  - ラピスバン
  - LiteBans
  - BanManagement
  - PlaceholderAPI
  - mcMMO
  - CrazyEnchantments
  - Train_Carts
commands:
  NOPE:
    usage: /<command>
    aliases:
      - ac
      - anticheat
      - ncp
permissions:
  nope.*:
    description: すべての NOPE 機能にアクセスし、すべての NOPE チェックをバイパスします
  nope.bypass.movement:
    description: プレイヤーがすべての移動チェックを回避できるようにします
  nope.bypass.flight:
    description: プレイヤーがすべてのフライトチェックをバイパスできるようにする
  "nope.bypass.movement.flight#4":
    description: "すべてのフライト#4チェックをバイパスすることをプレイヤーに許可する"
  nope.command.toggle.scoreboard:
    description: プレイヤーが自分のスコアボードを切り替えられるようにします
  nope.command.toggle.gscoreboard:
    description: プレイヤーがサーバーのスコアボードを切り替えられるようにします
  nope.command.testlag:
    description: プレイヤーがテストラグコマンドにアクセスできるようにします
  nope.command.false:
    description: Allows the player access to the false command
